services:
  backend:
    build:
      context: ../../
      dockerfile: ./docker/backend/app/Dockerfile
    container_name: backend
    hostname: backend.app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - redis

  db:
    build:
      context: ../../
      dockerfile: ./docker/backend/postgresql/Dockerfile
    container_name: db_postgresql
    hostname: backend.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: Asia/Tokyo
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    hostname: backend.redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgresql_data:
  redis_data:
