version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - 5432:5432
    container_name: db_postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --no-locale"
      TZ: Asia/Tokyo
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
