version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
    container_name: db_postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: Asia/Tokyo
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - redis
    container_name: backend

volumes:
  postgresql_data:
  redis_data:
