apiVersion: 1

datasources:
  - name: Prometheus(Mimir)
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9009/prometheus
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Mimir
      prometheusVersion: 2.7.x
      exemplarTraceIdDestinations:
        - datasourceUid: Tempo
          name: trace_id
  - name: Tempo
    type: tempo
    access: proxy
    url: http://host.docker.internal:3200
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'Loki'
        tags: [ 'job', 'instance', 'pod', 'namespace' ]
        mappedTags: [ { key: 'traceId', value: 'trace_id' } ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBYSpanID: false
      serviceMap:
        datasourceUid: 'Prometheus(Mimir)'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'Loki'
  - name: Loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: Tempo
          matcherRegex: "\\[[\\w-]+,(\\w*),"
          name: TraceID
          url: "$${__value.raw}"
