spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/book_manager
    username: book_manager
    password: book_manager
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: "book-manager"
logging:
  level:
    root: info
  pattern:
    console: "%d{ISO8601_OFFSET_DATE_TIME_HHCMM} %highlight{%-5level}[${spring.application.name:},%X{traceId},%X{spanId}] [%style{%t}{bright,blue}] %style{%C}{bright,yellow}: %m%n"
server:
  error:
    include-message: always
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
