spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/book_manager
    username: book_manager
    password: book_manager
  data:
    redis:
      host: redis
      port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info
server:
  error:
    include-message: always
