spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/book_manager
    username: book_manager
    password: book_manager
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: "book-manager"
logging:
  level:
    root: info
  pattern:
    console: "%d{${logging.pattern.dateformat}} %highlight{${logging.pattern.level}} [%style{%t}{bright,blue}] %style{%C}{bright,yellow}: %m%n"
    file: "%d{${logging.pattern.dateformat}} ${logging.pattern.level} [%t] %C: %m%n"
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  file:
    path: ./logs
    name: app.log
server:
  error:
    include-message: always
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
