spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/book_manager
    username: book_manager
    password: book_manager
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: info