services:
  db:
    image: postgres
    container_name: db_postgresql
    hostname: backend.db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
      TZ: Asia/Tokyo
    volumes:
      # 初期化スクリプトを docker-entrypoint-initdb.d に移動して実行させる
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis
    hostname: backend.redis
    volumes:
      - redis_data:/data
    networks:
      - redis
    ports:
      - "6379:6379"
volumes:
  postgresql_data:
  redis_data:
networks:
  # DBとRedisのネットワーク。アプリからアクセスする
  db:
    driver: bridge
    internal: false
    name: db_network
  redis:
    driver: bridge
    internal: false
    name: redis_network
