services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - datasource
    ports:
      - "9090:9090"
  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./config/tempo.yml:/etc/tempo.yml
      - tempo-data:/tmp/tempo
    networks:
      - datasource
    ports:
      - "3200:3200"   # tempo
      - "9411:9411"   # zipkin
  loki:
    image: grafana/loki
    container_name: loki
    command: [ "-config.file=/etc/config/loki-config.yml" ]
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./config/loki-config.yml:/etc/config/loki-config.yml
    networks:
      - datasource
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      TZ: Asia/Tokyo
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana
      - datasource
    ports:
      - "3000:3000"
volumes:
  grafana-storage:
  tempo-data:
networks:
  # Grafanaのネットワーク
  grafana:
    driver: bridge
    internal: false
    name: grafana_network
  # GrafanaのDataSources(Prometheus, Tempo, Loki)のネットワーク。SpringBootActuator と GrafanaAgentからアクセスするために公開
  datasource:
    driver: bridge
    internal: false
    name: datasources_network
